### ISSUE TITLE
View Access Token?

### ISSUE THREAD

**Issue by TomAafloen** [leeford/MSGraphAPIGUI#1]
Hello!
I realize this tool may not actively be updated, but I like it a lot for its simplicity (compared to Postman for instance) and I use it regularly.
Would it be possible to view/copy the access token that the tool acquires after successful authentication? For troubleshooting it helps to view the decoded Access Token on jwt.ms.
I believe it would not require that much code change to get a Copy Token button in the Authentication box, but full disclosure, I am not a developer. :-)

**Comment by TomAafloen** [comment]
I solved it by outputting the token to the Console.

To do this, I simply added the following line right before the line "**return $tokenRequest.Content**" in the functions *GetAuthTokenApplication*, *GetAuthTokenUser*, and *GetAuthTokenUserRefresh*:
`Write-Host $tokenRequest.Content | ConvertFrom-Json`

Thanks again for a great and simple tool!

**Comment by leeford** [comment]
No worries. Glad you find it useful!
